---
schema: 'deckhand/DataSchema/v1'
metadata:
  schema: metadata/Control/v1
  name: aqua/PluginConfig/v1
  labels:
    application: aqua
data:
  $schema: 'http://json-schema.org/schema#'
  definitions:
    databases_section:
      type: 'object'
      patternProperties:
        "^.*$":
          type: 'object'
          required:
            - user_id
            - password
          additionalProperties: false
          properties:
            db_url:
              type: 'string'
              pattern: ^.*:[0-9]{1,5}$
            user_id:
              type: 'string'
              minLength: 3
            password:
              type: 'string'
              minLength: 3
            scheme:
              type: 'string'
              pattern: ^.*\+.*$
            users:
              type: 'array'
              minItems: 1
              items:
                type: 'string'
    repositories_section:
      type: 'object'
      required:
        - docker
        - docker_open
      additionalProperties: false
      properties:
        docker:
          type: 'string'
        docker_open:
          type: 'string'
    uam_section:
      type: 'object'
      required:
        - uamroles
      additionalProperties: false
      properties:
        uamroles:
          type: 'string'
    ingress_section:
      type: 'object'
      required:
        - ingress_domain
      additionalProperties: false
      properties:
        ingress_domain:
          type: 'string'
    mm_section:
      type: 'object'
      additionalProperties: 
        name:
          "$id": "#/properties/data/properties/name"
          type: string
          title: Source Name
          default: ''
          examples:
            - ubuntu
            - linux_dell
        url:
          "$id": "#/properties/data/properties/url"
          type: string
          title: Source URL
          default: ''
          examples:
            - https://artifacts-nc.auk3.cci.att.com/artifactory/mirantis-dev-ceph/xenial
        key_url:
          "$id": "#/properties/data/properties/key_url"
          type: string
          title: Source Repository Public Key URL
          default: ''
          examples:
            - https://artifacts-nc.auk3.cci.att.com/artifactory/mirantis-dev-ceph/xenial/archive-ceph-mimic.key
        aptly_config:
          "$id": "#/properties/data/properties/aptly_config"
          type: string
          title: Aptly Config
          default: ''
          examples:
            - |
              {
                "rootDir": "/opt/.aptly",
                "downloadConcurrency": 4,
                "downloadSpeedLimit": 0,
                "architectures": ["amd64"],
                "dependencyFollowSuggests": false,
                "dependencyFollowRecommends": false,
                "dependencyFollowAllVariants": false,
                "dependencyFollowSource": false,
                "dependencyVerboseResolve": false,
                "gpgDisableSign": false,
                "gpgDisableVerify": false,
                "gpgProvider": "gpg",
                "downloadSourcePackages": false,
                "skipLegacyPool": true,
                "ppaDistributorID": "ubuntu",
                "ppaCodename": "",
                "FileSystemPublishEndpoints": {
                  "test": {
                    "rootDir": "/opt/aptly-publish",
                    "linkMethod": "copy",
                    "verifyMethod": "md5"
                  }
                },
                "S3PublishEndpoints": {
                  "test": {
                    "region": "us-east-1",
                    "bucket": "repo",
                    "endpoint": "",
                    "awsAccessKeyID": "",
                    "awsSecretAccessKey": "",
                    "prefix": "",
                    "acl": "public-read",
                    "storageClass": "",
                    "encryptionMethod": "",
                    "plusWorkaround": false,
                    "disableMultiDel": false,
                    "forceSigV2": false,
                    "debug": false
                  }
                },
                "SwiftPublishEndpoints": {
                  "test": {
                    "container": "repo",
                    "osname": "",
                    "password": "",
                    "prefix": "",
                    "authurl": "",
                    "tenant": "",
                    "tenantid": "",
                    "domain": "",
                    "domainid": "",
                    "tenantdomain": "",
                    "tenantdomainid": ""
                  }
                }
              }
        components:
          "$id": "#/properties/data/properties/components"
          type: array
          title: Source Repository Components
          items:
            "$id": "#/properties/data/properties/components/items"
            type: string
            title: APT Repository Component
            default: ''
            examples:
              - main
              - universe
              - multiverse
        subrepos:
          "$id": "#/properties/data/properties/subrepos"
          type: array
          title: APT Sub-repositories
          items:
            "$id": "#/properties/data/properties/subrepos/items"
            type: object
            title: APT Sub-repository
            required:
              - distribution
              - packages
            properties:
              distribution:
                "$id": "#/properties/data/properties/subrepos/items/properties/distribution"
                type: string
                title: Ubuntu Distribution
                default: ''
                examples:
                  - xenial
                  - xenial-updates
                  - bionic
                  - bionic-updates
              packages:
                "$id": "#/properties/data/properties/subrepos/items/properties/packages"
                type: array
                title: APT Packages
                items:
                  "$id": "#/properties/data/properties/subrepos/items/properties/packages/items"
                  type: object
                  title: APT Package
                  required:
                    - name
                  properties:
                    name:
                      "$id": "#/properties/data/properties/subrepos/items/properties/packages/items/properties/name"
                      type: string
                      title: Package Name
                      default: ''
                      examples:
                        - tmux
                        - vim
                    version:
                      "$id": "#/properties/data/properties/subrepos/items/properties/packages/items/properties/version"
                      type: string
                      title: Package Version
                      default: ''
                      examples:
                        - 13.2.4-2~u16.04
    # Defines the plugin_config - all possible options
    # Could make this more specific in the future to be defined per plugin
    plugin_config:
      type: 'object'
      additionalProperties: false
      properties:
        databases:
          $ref: "#/definitions/databases_section"
        repositories:
          $ref: "#/definitions/repositories_section"
        mm:
          $ref: "#/definitions/mm_section"
        uam:
          $ref: "#/definitions/uam_section"
        ingress:
          $ref: "#/definitions/ingress_section"
  # Allow for any named plugin_config to exist
  type: 'object'
  patternProperties:
    "^.*$":
      $ref: "#/definitions/plugin_config"
