name: preflight-checks
on:
  push:
    branches:
    - master
    - release-*
  pull_request:
    branches:
    - master
    - release-*

jobs:
  go_unit_tests:
    strategy:
      matrix:
        go-version:
          - 1.13.x
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Golang tests on ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Set GOPATH
        # temporary fix
        # see https://github.com/actions/setup-go/issues/14
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - name: run_go_tests
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go test

  node_unit_tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Karma tests on ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1.1.0
      - uses: actions/checkout@v2
      - name: run_karma
        run: |
          cd web
          npm ci
          npm run test:headless

  bundle_assets:
    needs: [go_unit_tests, node_unit_tests]
    strategy:
      matrix:
        go-version:
          - 1.13.x
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Build on ${{ matrix.platform }}
    steps:
      - uses: actions/setup-node@v1.1.0
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Build node modules
        run: |
          cd web
          npm ci
          npm run-script build
      - name: Set GOPATH
        # temporary fix
        # see https://github.com/actions/setup-go/issues/14
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - name: Go tools
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go go-install
          go generate ./web ./pkg/icon
      - name: Build binary
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go build
      # - name: release
      #   uses: goreleaser/goreleaser-action@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload icons
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: icons-${{ matrix.platform }}
      #     path: pkg/icon/rice-box.go
      # - name: Upload web
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: web-${{ matrix.platform }}
      #     path: web/rice-box.go
