name: Verify generated code
on:
  push:
    branches:
    - master
    - release-*
  pull_request:
    branches:
    - master
    - release-*
jobs:
  verify_generated:
    name: Verify generated code
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set GOPATH
        # temporary fix
        # see https://github.com/actions/setup-go/issues/14
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - name: Verify generated code
        run: ci/check-generated-mocks.sh

